#!/bin/bash

source gkc-utils.sh

get_help() {
    printf "Creates a new branch with the issue ID in you computer
and move it to stage In Progress on github.

 Usage:
    gkc-task-start issueID

 Ex:
    gkc-task-start 3084

    \n"

}


validCredentials

issue_number=$1

if [[ -z $1 ]] || [[ $@ =~ --help ]]
then
    get_help
    exit 0
fi

exists=$(curl -s $COMMAND "$AUTHORIZATION" https://api.github.com/repos/"$REPO_PATH"/issues/"$issue_number" | grep message)
if [[ $exists == *"Not Found"* ]]; then
    printf "\e[33mNo issue with this ID was found\e[0m\n"
fi

git stash || true

git checkout master

git fetch origin
git submodule update --recursive --remote

if [[ $(git branch | grep "$issue_number") ]]; then
    printf "\e[33mThis branch already exists. Checking out on it.\e[0m\n"
    git checkout "$issue_number"
else
    git checkout -b "$issue_number" origin/master
    gkc-issue-tag --rm 'Stage: Analysis' $issue_number
    gkc-issue-tag --add 'Stage: In Progress' $issue_number
fi
